name: Unit Test

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v4
      - name: Setup Node
        uses: action/setup-node@v4
      - run: npm ci
      - run: npm test
